### ISSUE TITLE
Reopening hardware components

### ISSUE THREAD

**Issue by LupusTheEngineer** [HerobrinesArmy/DevCPU#1]
Version 0.0.0: devcpu.win32.win32.x86_64

I found it impossible to re-open the windows of Hardware (such as the LEM, SPED-3 or Generic Keyboard) after closing them for the first time. You can work around it by destroying and replacing the Hardware in question.

I figured I had to mention this 'bug' here. Herobrine already assured me he was planning to fix it. 
![DevCPUv0 0 0](https://f.cloud.github.com/assets/3451593/321804/71000854-9a0e-11e2-841f-167252c106d2.png)

**Comment by HerobrinesArmy** [comment]
This bug exists in all versions of DevCPU and I've known about it for quite some time. It is at the top of a long list of known issues that I'll be fixing. The recommended workaround is to open a new view for that hardware type (from the Window menu) and attach the hardware to it using the dropdown menu in the corner of the view. There is no need to destroy the hardware.

**Comment by Yamakaky** [comment]
For not repeating yourself, you should write a 'next-release' file with bugs you know ^^
