### ISSUE TITLE
Lexer bug

### ISSUE THREAD

**Issue by Yamakaky** [HerobrinesArmy/DevCPU#11]
strange bug : if a label begins with 'pop', compilation fails. For example, `jsr pop_regs` fails, but not `jsr push_regs` or an other label…

Error : `Assembly failed: Lexer's branching matcher sets could not find a syntactically valid way to tokenize …`

**Comment by HerobrinesArmy** [comment]
Nice one. I'll be pushing a fix for this shortly. Thanks for the report!

**Comment by Yamakaky** [comment]
thx, was fast !
