### ISSUE TITLE
The keyboard can't be activated

### ISSUE THREAD

**Issue by Lucus16** [HerobrinesArmy/DevCPU#14]
The keyboard is not working on a lot of platforms. There is no way to activate it, clicking the panel does nothing.

**Comment by HerobrinesArmy** [comment]
I'm pushing an update that should fix this. It fixed it on the one platform I've used that experienced the issue. Thanks for the report!

**Comment by StillNoNumber** [comment]
Well, since somebody already did it, I won't send another request as Herobrine told me on the other forums :)
