### ISSUE TITLE
Getting a "not authorized" while trying to push to github.

### ISSUE THREAD

**Issue by L3nn0x** [HerobrinesArmy/DevCPU#18]
I've created a clone for a github project, then I loaded it in DevCPU. I syncrhonized it, everything was alright. Then I tried commit and push, but I got a "not authorized" error, even though I entered my account informations in "Select an URL" subwindow. It just doesn't seem to keep them in memory.

By the way, the "Store in secure store" button doesn't work : "Writing to secure store failed
No secure storage modules found."

Thanks for reading.

**Comment by HerobrinesArmy** [comment]
Whatever the problem is, it isn't likely that it has anything to do with DevCPU. All of the Git stuff is handled by the EGit plugin. It literally required no configuration or integration with DevCPU. What platform are you on? OS X, by any chance?

**Comment by L3nn0x** [comment]
Nope, I'm using a 32 bits debian. I'll try looking at the options more un detail.

**Comment by Yamakaky** [comment]
I'm on OS X, if you want debug infos

**Comment by HerobrinesArmy** [comment]
Lucus was having what sounded virtually identical to this issue. He eventually figured something out. You might want to talk to him.

**Comment by L3nn0x** [comment]
Okay, I'll talk to him, thanks.
