### ISSUE TITLE
Recent changes cause application to freeze after extended use

### ISSUE THREAD

**Issue by HerobrinesArmy** [HerobrinesArmy/DevCPU#19]
Recent changes cause DevCPU to freeze after extended use. This needs to be corrected before Release 0 Update 0.

**Comment by HerobrinesArmy** [comment]
This is really bothering me. -_-

**Comment by HerobrinesArmy** [comment]
This is all that's stopping me from putting out Release 0 Update 0 at this point.

**Comment by L3nn0x** [comment]
Maybe it's because of some sort of memory leak? (It's just an idea.)

**Comment by HerobrinesArmy** [comment]
After my latest attempt to fix this problem, I have been unable to reproduce the problem on two different platforms. I am closing this issue. If anyone else experiences this problem after Release 0 Update 0 (and I expect some other platforms will experience something like it anyway), open a new issue.
