### ISSUE TITLE
Make a feature to assemble from custom address!

### ISSUE THREAD

**Issue by DankRank** [HerobrinesArmy/DevCPU#26]
for example, i got program w/ a :label in it.
I'm gonna load that program from FDD to 0x7000.
yeah, that is hard to do, so label work, cause all labels was counted from 0x0000 address.

its gonna be much easier, if there was a function, that will count labels from custom address, like 0x7000.

**Comment by HerobrinesArmy** [comment]
DevCPU supports several origin movement directives.
Try:

<pre>.org 0x7000</pre>

**Comment by DankRank** [comment]
ok, but how do it works? i wanna so it's got assembled from 0x0000 on FD, but labels, need to computed from 0x7000.

**Comment by DankRank** [comment]
also, what other pre-processing functions, DevCPU supports?
