### ISSUE TITLE
Old version published as "Release 0 Update 0"

### ISSUE THREAD

**Issue by HerobrinesArmy** [HerobrinesArmy/DevCPU#29]
NOTICE: If you have downloaded Release 0 Update 0, you got a bad version. You do not have Release 0 Update 0. Remove it. Once this build issue is resolved, there will be an announcement of the re-launch of Update 0.

**Comment by HerobrinesArmy** [comment]
Correct versions of all files have now been posted at http://devcpu.com/dl.php

**Comment by Yamakaky** [comment]
Mac version isn't launching… I see the splash screen, but no progress bar.

**Comment by HerobrinesArmy** [comment]
Nuuuuu

**Comment by L3nn0x** [comment]
Strange enough, I downloaded the one from yesterday, and it is the new version. (I downloaded the linux x86 one.) It's working pretty nicely too. :)

**Comment by HerobrinesArmy** [comment]
Well, I've taken this opportunity to make a few improvements to increase the useful life of 0_0 while people are waiting for Release 1. I'll re-release in less than 12 hours.

**Comment by L3nn0x** [comment]
Nice. :)

**Comment by Yamakaky** [comment]
Cool !

**Comment by HerobrinesArmy** [comment]
Alright, I'm about to put these things back up and quit screwing with them, so I'm closing this.
