### ISSUE TITLE
Not Loading on Mac OSX

### ISSUE THREAD

**Issue by ghost** [HerobrinesArmy/DevCPU#31]
On DevCPU for Mac OSX x86 it will display the splash screen and not do anything. No loading bar, nothing.

**Comment by HerobrinesArmy** [comment]
1. Does it crash, or just not ever load? Or something else?
2. Have you tried previous versions on that machine, and did they work?
3. Do you have Java 6 or Java 7?

**Comment by HerobrinesArmy** [comment]
1. More importantly, when did you download it. You posted this 27 minutes ago, but I didn't think I'd even turned the download page back on yet 27 minutes ago. 0_o

**Comment by HerobrinesArmy** [comment]
Thank you, GitHub, for deciding that "4." should show up as "1." instead. ![:wth:](http://herobrinesarmy.com/smileys/wth_by_i_is_smart-d4g7pg4.png)

**Comment by ghost** [comment]
1. It never loads. No crash.
2.  Yes
3. I don't know, I'll have to check that later
4. I downloaded it just before i posted this. I tested it again after you announced it just for good measure, identical problem

**Comment by Yamakaky** [comment]
I have the same, on x86 and x86_64. I use java 7. I just downloaded it

**Comment by HerobrinesArmy** [comment]
Can someone on a Mac who knows much about Java check to see what's being printed to the Java console when it tries to load?

**Comment by HerobrinesArmy** [comment]
By the way, if it was working before but isn't now, there's something you can try, if you still have the old one, Go into the "plugins" folder of the new one, and copy "DevCPU_0.0.0.jar" into the "plugins" folder of the old one and try running the old one instead. If you do that, please report back to let me know if it worked, and if not, what it did. Thanks. That'll help me to remotely debug this.

**Comment by HerobrinesArmy** [comment]
Silly Close button. Why must you sit so close to the Comment button?

**Comment by ghost** [comment]
Due to OS X 10.6.8, I cannot download a newer version of java than 6. I ran a software update for good measure and the problem still existed.

here's a copy of the console message it gives:
Apr 14 16:22:05 Kevins-MacBook-Pro-15 /Users/kevin/Desktop/untitled folder/DevCPU 2/DevCPU.app/Contents/MacOS/DevCPU[15616]: Unrecognized Java VM option ignored: -XstartOnFirstThread
Apr 14 16:22:08 Kevins-MacBook-Pro-15 DevCPU[15616]: [Java CocoaComponent compatibility mode]: Enabled
Apr 14 16:22:08 Kevins-MacBook-Pro-15 DevCPU[15616]: [Java CocoaComponent compatibility mode]: Setting timeout for SWT to 0.100000

I tried opening the java console for that application but when I did nothing happened. I think it's a bug with java 6 itself.

When I tried your fix, the same thing happened.

**Comment by Yamakaky** [comment]
It's the .jar. I tried to pour it in my previous DevCPU folder, but I's not working.

http://pastebin.com/bGiAzHfd
It's system.log, it appears when I launch the app (not sure the end is important).

**Comment by Yamakaky** [comment]
Thanks to `git bisect`, it seems that the first wrong commit is 07c320a7.

**Comment by HerobrinesArmy** [comment]
I pushed a change that might help Mac users with OSX's failure to support the JVM properly.

**Comment by Yamakaky** [comment]
It works \o/

**Comment by HerobrinesArmy** [comment]
Huzzah! I'll rebuild it later and replace the ones on the download page.

**Comment by HerobrinesArmy** [comment]
Thanks for all of your reports, by the way. I wouldn't have been able to do anything without them.

**Comment by Yamakaky** [comment]
`git bisect` is good. Use it. ^^
