### ISSUE TITLE
Readability of numbers

### ISSUE THREAD

**Issue by Yamakaky** [HerobrinesArmy/DevCPU#36]
It may be cool to be able to write numbers like this : 
0b1011 1001 1001 0001
or maybe like that : 
0b1011_1001_1001_0001

**Comment by L3nn0x** [comment]
Who wanna write in binary anyways? Stick to hexa, it's way better.

**Comment by HerobrinesArmy** [comment]
Unfortunately, I don't think I'm going to support any number format that has spaces. I'll consider whether to strip underscores from strings of 1s and 0s, but it probably isn't going to happen. Right now, the numeric forms supported are:
12435 for decimal
0x89ab for hexadecimal
0b1010101010100110 for binary
and I think that's it.

**Comment by Yamakaky** [comment]
Ok
