### ISSUE TITLE
Supported characters in label names

### ISSUE THREAD

**Issue by rgarlor** [HerobrinesArmy/DevCPU#39]
Actually, the label names can have the character ":" (other compilers don't support it) and works well, but this character cannot be placed in the "set" instruction. So, I think that would be useful to allow it in the "set" instruction or directly don't allow this character to be placed in label names, either.
Example:

``` assembly
:some:label    ; works
    bla
    bla
    bla


set pc, some:label    ; doesn't work
```

**Comment by HerobrinesArmy** [comment]
<pre>:some:label</pre> declares two labels, one named some and one named label.

**Comment by HerobrinesArmy** [comment]
DevCPU is as forgiving as possible on spacing.

**Comment by s-ol** [comment]
You should close this issue.

**Comment by HerobrinesArmy** [comment]
That's very true. Thanks.
