### ISSUE TITLE
Multiline Comments

### ISSUE THREAD

**Issue by s-ol** [HerobrinesArmy/DevCPU#41]
Commenting out a bunch of code sucks, so how about "C-Style" comments with `/*` and `*/` or comments like this:

``````
;;; Comment start
still a comment here
and even now!;;;
this is no comment anymore :'(```
``````

**Comment by HerobrinesArmy** [comment]
You'll be able to highlight a bunch of code and hit ctrl+/ or ctrl+; to comment out/in all of the selected lines (the way it works with Java code in Eclipse). Will that be satisfactory?

**Comment by s-ol** [comment]
probably enough.
