### ISSUE TITLE
Assembler doesn't assemble

### ISSUE THREAD

**Issue by ghost** [HerobrinesArmy/DevCPU#5]
Using DevCPU release 0, cocoa version for x86 mac.

I've been trying to get the assembler to actually write something to either a disk or a DCPU, both of them. It does not assemble to binary, when I assemble to disk and then dump the disk to a file the file is 1.5 megabytes of null bytes. This seems to be a very large issue, for me at least.

**Comment by HerobrinesArmy** [comment]
What do you mean it's a text file? What does it say in the file? What text?

**Comment by ghost** [comment]
ah, I take it back. It just writes nothing to the file(earlier I had already tried to write to a disk, which wrote the source code)

**Comment by HerobrinesArmy** [comment]
Wait a minute....what file extension are you using for your source files?

**Comment by ghost** [comment]
.dasm

**Comment by ghost** [comment]
I'm doing a more extensive test to see if it's just a problem with dumping the data

**Comment by HerobrinesArmy** [comment]
Are you sure you're selecting "Assemble to DCPU..." because the behavior you described is exactly what would happen if you selected "Write to DCPU..." instead.

**Comment by ghost** [comment]
absolutely sure.

**Comment by ghost** [comment]
it gives me a ton of "argument cannot be null" errors as well.

**Comment by HerobrinesArmy** [comment]
I don't believe you...

**Comment by ghost** [comment]
http://www.filedropper.com/howtocausebug

**Comment by ghost** [comment]
github can't deal with TIFF images.

**Comment by HerobrinesArmy** [comment]
I think you're seeing a combination of things here. First, your real program probably isn't assembling. Sure, "it works on other assemblers" but "other assemblers" do different things. You're probably using directives they use but that DevCPU doesn't, or operators DevCPU doesn't. At Release 0, DevCPU only supported +, -, *, and / operators, and grouping with '(' and ')', or you have a label definition at the beginning of a line with a directive on it, or something like that. You don't have your console visible in those screenshots, so I can't tell. The TEST file probably assembled just fine, and you're seeing a different problem when you try to open it. Release 0 wasn't closing the output stream properly for "Dump RAM to file" so the buffer probably never gets written to the file. This was fixed this morning (Issue #4). Unfortunately, Release 0 doesn't have very good error reporting. Some were silent, some incredibly nonspecific. They're better now, and will continue to improve, but that's not going to help you much until Release 0 Update 0, which is when I end support for the pre-release version.

**Comment by ghost** [comment]
Good taknow nobody will be experiencing that problem. :)
