### ISSUE TITLE
Assembler ignoring incorrect instructions

### ISSUE THREAD

**Issue by Lucus16** [HerobrinesArmy/DevCPU#8]
I tried assembling the following piece of code and to my surprise, it didn't give me an error.

```
set
add 5
hwi i, j
set pc, pop
```

It told me the assembled size was 1 word, presumably generated from the last instruction. It seems that if the lexer fails to lex a line, it doesn't give an error.

**Comment by HerobrinesArmy** [comment]
This behavior should already be changed, such that it now throws an exception. One of the commits yesterday was to replace a bunch of "//TODO Throw exception"s with actual exception throws. Before that, the behavior of line 1 and 3 in your example would have been to print "Error" to the Java console (not to be confused with DevCPU's console). So, I'll go ahead and mark this closed. Thanks for the report!
