### ISSUE TITLE
In my memory dump : "Out of memory"

### ISSUE THREAD

**Issue by azertyfun** [HerobrinesArmy/DevCPU#9]
Hello !

I'm trying to make my 0x10c-devkit project run into DevCPU. However, it doesn't work. So I compiled my boot file into a floppy, and I dumped it into a file. When I opened with an hexadecimal editor, I saw that my dump says that : <pre>Error. The actual program tryed to allocate too much memory. The system will crash. Press any key to continue...</pre>
I think it's a problem when I assemble, because my DCPU goes from 0000 to 00F0 until SP = 0.
Here is my project with the dump inside : ftp://azertyfun.tk/SimpleOS%20v2%20DevCPU%20compatible.zip

**Comment by HerobrinesArmy** [comment]
![:wth:](http://herobrinesarmy.com/smileys/wth_by_i_is_smart-d4g7pg4.png)

**Comment by HerobrinesArmy** [comment]
That's a String in your code.

<pre>:error_notEnoughFreeSpace DAT "Error. The actual program tryed to allocate too much memory. The system will crash. Press any key to continue...", 0</pre>

I'm not exactly sure what you're saying the problem is.

**Comment by Yamakaky** [comment]
Yes, he's right XD Look in DATA/DATA.dasm

**Comment by azertyfun** [comment]
Holly sh*t. But why does it write that into my floppy ? It should never write that on the screen, my scheduler is not used. Sorry xD

**Comment by Yamakaky** [comment]
It's written on the floppy because it's on your source. During the compilation, it's "encoded" in ascii so you can read it with a text or hex editor.

**Comment by azertyfun** [comment]
I don't understand what you mean, it should'nt write a single text into this floppy. If it was all the OS I could understand, but there is no reason for writing just that. I'll check that...
EDIT : Ok I understood. The files are inclued in the same order than the #includes. And my first include was the DATA.dasm, but it's ok now.
